title: Trinath Panda's Blog
description: "A tech blog sharing thoughts, ideas, and experiences"
author:
  name: "Trinath Panda"
  email: "pandatrinath1999@gmail.com"
  url: "https://trinathp.github.io/index.html"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 12
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Trinath Panda"
year : "2025"